export const APP_ACTIONS = {
    // dialogReducer
    ADD_POST: 'ADD_POST',
    SEND_MESSAGE: 'SEND_MESSAGE',
    UPDATE_NEW_POST_TEXT: 'UPDATE_NEW_POST_TEXT',
    UPDATE_NEW_MESSAGE_TEXT: 'UPDATE_NEW_MESSAGE_TEXT',
    // userReducer
    FOLLOW: 'FOLLOW',
    UNFOLLOW: 'UNFOLLOW',
    SET_USERS: 'SET_USERS',
    SET_PAGE: 'SET_PAGE',
    SET_TOTAL_COUNT: 'SET_TOTAL_COUNT',
    IS_FETCHING: 'IS_FETCHING',
    IS_DISABLED_BTN: 'IS_DISABLED_BTN',
    // profileReducer
    SET_PROFILE_DATA: 'SET_PROFILE_DATA',
    GET_STATUS: 'GET_STATUS',
    // authReducer
    SET_AUTH_DATA: 'SET_AUTH_DATA',
}